// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEtoN5-dvMz5f2qjVhIPp6djdg80bQUjQ',
    appId: '1:498553818376:web:2fc656f69d55f34dd770bd',
    messagingSenderId: '498553818376',
    projectId: 'basics-aac0f',
    authDomain: 'basics-aac0f.firebaseapp.com',
    storageBucket: 'basics-aac0f.appspot.com',
    measurementId: 'G-5486QFREL6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQ5h1HxyXn-LtJzGlFN-f6k-PP8JpDDeQ',
    appId: '1:498553818376:android:936f991d84e88a06d770bd',
    messagingSenderId: '498553818376',
    projectId: 'basics-aac0f',
    storageBucket: 'basics-aac0f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCfKhrm872dS5tjaXce4om7XSKh3-G72o',
    appId: '1:498553818376:ios:a8b00e7995d1959cd770bd',
    messagingSenderId: '498553818376',
    projectId: 'basics-aac0f',
    storageBucket: 'basics-aac0f.appspot.com',
    iosClientId: '498553818376-iihjko0lrv2ql64ssd6564i7fq4oefu1.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );
}
